### ISSUE TITLE
Rename variables

### ISSUE THREAD

**Issue by ecumene** [millerm30/chore-bucks#12]
https://github.com/millerm30/chore-bucks/blob/ecef803d83079cd9718532455e1c2a7d53a16c27/src/components/Choresadd.js#L26

 - [x] `newchore` -> `label`
 - [x] `setnewChore` -> `setLabel`
 - [x] `updateMyArray` -> `setChoresList`
 - [x] `myArray` -> `choresList`
 - [x] `Choresadd` -> `ChoresAdd`

**Comment by millerm30** [comment]
Completion of rename of variables.
