### ISSUE TITLE
Finish shopping cart system

### ISSUE THREAD

**Issue by ecumene** [millerm30/chore-bucks#14]
- [x] Selecting items store them away in localstorage
 - [x] Deducts from the user's points
 - [x] Remove it from the wishlist???

**Comment by jackharrhy** [comment]
Notes from June 22nd:

Wishlist being its own thing without proper drilling / provider is _fine_

Cart should have a provider similar to Chores ( you can probably just copy Chores.js is `contexts`), that will have its own useChores
Wishlist will invoke the 'addToCart' from this Cart provider
the Cart page will likely display all items in the Cart, and invoke other functions in the Cart provider
similar to Chores, everything to do with localStorage should live in the Cart provider

**Comment by millerm30** [comment]
Added Shopping provider and added wishlist items to shopping cart complete. Added cart items to local storage as well added total cart purchase cost to cart screen! I need a drink after that! 
![image](https://user-images.githubusercontent.com/95964613/175817454-8ff1c2ba-e9d6-4d02-b878-b38d81ef1e66.png)

**Comment by jackharrhy** [comment]
Complete https://github.com/millerm30/chore-bucks/issues/20

**Comment by millerm30** [comment]
Shopping cart completed. Ready to smash those chores and earn money!
