### ISSUE TITLE
Look into using `usePersistedState` across the app (optional)

### ISSUE THREAD

**Issue by ecumene** [millerm30/chore-bucks#16]
[Code](https://gist.githubusercontent.com/DamianoMagrini/47baa1d93d965879625694bd83fe199a/raw/98500ea30c68c5b1d5680aa93e7dd478a1c95a7e/5.js) [Article](https://levelup.gitconnected.com/react-localstorage-persisting-state-with-a-custom-hook-98f9a88ae7a9)

**Comment by millerm30** [comment]
Going to wait on this implementation as this project might end up using a back end.
