### ISSUE TITLE
Export / Import localStorage

### ISSUE THREAD

**Issue by jackharrhy** [millerm30/chore-bucks#18]
In the top right of the screen, include a button to 'export'

- [ ] Export
hitting export, should read everything from localStorage that is specific to the app (points, wishlist, cart, chores, etc.), and put it into one big object
that object should be then stringiifed to json, and written to disk

( for downloading files, i would put the function found in https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server called download into its own file, and export it elsewhere )

---

- [ ] Import
another button next to export should be import, it will do the opposite of the above, it will read a file outputted from export, and override all of localStorage from the contents of the file

**Comment by millerm30** [comment]
Going to wait on this idea as project will possibly be used for nodeJS
