### ISSUE TITLE
Bake in concept of 'users', but do via local storage

### ISSUE THREAD

**Issue by jackharrhy** [millerm30/chore-bucks#19]
In the Router, read from `current-user` from localStorage,
if the value is null, assume the user is not logged in, and they should log in, therefore do not show the app UI, but show a username and password screen regardless of what path they are on

once the user puts in a username and password on this screen, check if the username and password combo is valid
you can store users in localStorage in an object if you want, maybe like so:

```js
{
  "joe": "passwordforjoe"
  "jane": "janepassword123"
}
```

if the combo is valid, set the current user to the username they put in, and ensure they can then navigate the app
in the top right corner of the screen show the users username

if the combo is invalid, show red text telling if the username was not found, or the password was invalid

**Comment by jackharrhy** [comment]
this will likely have to be done before #17 such that the information required to send a notification is contained within localStorage and not in the code, therefore not on github

**Comment by jackharrhy** [comment]
```js
  const isLoggedIn = false;

  return (
    <App points={points} addPoints={addPoints} removePoints={removePoints}>
      <BrowserRouter basename="/chore-bucks">
        <Routes>
          {isLoggedIn ? (
            <Route path="/" element={<Layout points={points} />}>
              <Route path="" element={<HeroPage />} />
              <Route path="/chores" element={<ChoresPage />} />
              <Route path="/choresadd" element={<ChoresaddPage />} />
              <Route path="/wishlist" element={<WishlistPage />} />
              <Route path="/cart" element={<Cart points={points} />} />
            </Route>
          ) : (
            <Route path="*" element={<p>Login page</p>} />
          )}
        </Routes>
      </BrowserRouter>
    </App>
  );
  ```

**Comment by millerm30** [comment]
Start of user setup. Added login page and initial setup for user provider. Disabled isLoggedIn for now to allow working for now...

**Comment by jackharrhy** [comment]
- [ ] ensure that the provider that contains `isLoggedIn`, is _above_ the routes, in such a way that you can access `isLoggedIn` and it will not be undefined

**Comment by millerm30** [comment]
I'm gettin' there!

**Comment by millerm30** [comment]
User login / logout setup and all seems to be working. My head hurts after this one! LOL
