### ISSUE TITLE
Fun additions

### ISSUE THREAD

**Issue by jackharrhy** [millerm30/chore-bucks#24]
- [x] use https://www.npmjs.com/package/react-confetti somehow, so certain actions in the app drop confetti

- [x] #25

```jsx
                          <motion.button
                            whileHover={{ scale: 1.1 }}
                            whileTap={{ scale: 0.9 }}
                            type="submit"
                            disabled={!chore}
                            className={`bg-blue-900 my-4 self-center px-4 py-2 text-white font-bold rounded-lg ${
                              !chore
                                ? "opacity-50 cursor-not-allowed"
                                : "cursor-pointer"
                            }`}
                          >
                            Add Chore
                          </motion.button>
```

You can probably make a reusable button component if you want that encapsulates the motion.button stuff

- [ ] add way to 'walk through' a user in the app for the first time with clickable help boxes bringing them through signing in, creating a chore, completing it, etc.

**Comment by millerm30** [comment]
Completion of framer motion and confetti add to various screens
