### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by millerm30** [millerm30/chore-bucks#4]
Unique Id / Key required for chores list to be added.

**Comment by jackharrhy** [comment]
```js
  const addChore = (chore) => {
    toast.success(`${chore} added to chores list!`);
    setChores([...chores, { id: uuid(), chore }]);
  };
  ```
example add chore

**Comment by millerm30** [comment]
Start of unique key add for chores.
error code
"Objects are not valid as a React child (found: object with keys {id, chore}). If you meant to render a collection of children, use an array instead."
